runtime: nodejs14

env_variables:
  SECRET: "hyper@loop(^^4&23encrtyped%#!@secret"
  DB_CONNECTION_STRING: "MongoDBConnectionString"

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto